artemis/README.md, artemis/crds/broker_activemqartemis_crd.yaml, artemis/crds/broker_activemqartemisaddress_crd.yaml, artemis/crds/broker_activemqartemisscaledown_crd.yaml, artemis/crds/broker_activemqartemissecurity_crd.yaml, artemis/election_role.yaml, artemis/election_role_binding.yaml, artemis/kustomization.yaml, artemis/operator.yaml, artemis/operator_config.yaml, artemis/role.yaml, artemis/role_binding.yaml, artemis/service_account.yaml, environments/dev/artemis-deployments.yaml, environments/dev/kustomization.yaml, environments/dev/passport-status-api-configmaps.yaml, environments/local/artemis-deployments.yaml, environments/local/kustomization.yaml, environments/local/passport-status-api-configmaps.yaml, environments/staging/artemis-deployments.yaml, environments/staging/kustomization.yaml, environments/staging/passport-status-api-configmaps.yaml
Add and configure ArtermisMQ Artemis based on [ArtemisCloud.io](https://artemiscloud.io/docs/getting-started/introduction/).
=> Add and configure ArtermisMQ Artemis

README.md, base/postgresql-ha/README.md, environments/test/artemis-deployments.yaml, environments/test/kustomization.yaml, environments/test/passport-status-api-configmaps.yaml, environments/test/passport-status-api-deployments.yaml, environments/test/passport-status-api-ingresses.yaml, environments/test/passport-status-frontend-configmaps.yaml, environments/test/passport-status-frontend-deployments.yaml, environments/test/passport-status-frontend-ingresses.yaml
Adding test environment specifications.
=> Add test deployment

environments/staging/kustomization.yaml, environments/test/kustomization.yaml
Bump frontend test/staging to 20221223-189-3c975cb1
=> Bump frontend test/staging to 20221223-189-3c975cb1

base/passport-status-api/deployments.yaml
=> Increase API resources

base/passport-status-api/deployments.yaml
Reverts DTS-STN/passport-status-gitops#17
=> Revert "Increase API resources"

base/passport-status-api/deployments.yaml
Reverts DTS-STN/passport-status-gitops#16
=> Revert "Increase CPU limits for API"

base/passport-status-api/deployments.yaml, base/passport-status-frontend/deployments.yaml, environments/dev/passport-status-api-deployments.yaml, environments/local/passport-status-api-deployments.yaml, environments/nightly/passport-status-api-deployments.yaml, environments/nightly/passport-status-frontend-deployments.yaml, environments/prod/passport-status-api-deployments.yaml, environments/prod/passport-status-frontend-deployments.yaml, environments/staging/passport-status-api-deployments.yaml, environments/staging/passport-status-frontend-deployments.yaml
Reverts DTS-STN/passport-status-gitops#15
=> Revert "Lower resource limits to bring inline w/ dynatrace"

environments/prod/kustomization.yaml, environments/prod/passport-status-api-deployments.yaml, environments/prod/passport-status-api-hpas.yaml, environments/prod/passport-status-frontend-deployments.yaml, environments/prod/passport-status-frontend-hpas.yaml, environments/staging/kustomization.yaml, environments/staging/passport-status-api-deployments.yaml, environments/staging/passport-status-api-hpas.yaml, environments/staging/passport-status-frontend-deployments.yaml, environments/staging/passport-status-frontend-hpas.yaml
HorizontalPodAutoscalers added.. minimum 2 instances; maximum 20.
🤙
=> Add HPAs to prod/staging

environments/nightly/passport-status-frontend-configmaps.yaml, environments/prod/passport-status-frontend-configmaps.yaml, environments/staging/passport-status-frontend-configmaps.yaml, environments/test/passport-status-frontend-configmaps.yaml
=> Modify frontend API URL to use default port (80)

environments/staging/kustomization.yaml, environments/test/kustomization.yaml
Bump API version in test and staging.
=> Bump API to 20230120-00328-13ba9afb

environments/staging/kustomization.yaml, environments/test/kustomization.yaml
=> Bump API to `20230127-00333-7d6c9a89`

environments/prod/passport-status-api-configmaps.yaml
=> Remove request logging for production

base/passport-status-frontend/deployments.yaml
As per title.
See <https://cloud.ibm.com/docs/containers?topic=containers-update_app>
=> Configure rollout instantaneous switch

environments/dev/kustomization.yaml, environments/dev/passport-status-frontend-configmaps.yaml, environments/dev/passport-status-frontend-deployments.yaml, environments/dev/passport-status-frontend-ingresses.yaml
These manifests has been applied.
=> Add dev frontend manifests

environments/prod/kustomization.yaml
Strike is over, downgrading to previous used version before strike.
=> Downgrade PROD to preivous used version

base/postgres-operator/README.md, base/postgres-operator/kustomization.yaml, base/postgres-operator/manager-upgrade.yaml, base/postgres-operator/manager.yaml, base/postgres-operator/role-upgrade.yaml, base/postgres-operator/role.yaml, base/postgres-operator/role_binding-upgrade.yaml, base/postgres-operator/role_binding.yaml, base/postgres-operator/selectors.yaml, base/postgres-operator/service_account-upgrade.yaml, base/postgres-operator/service_account.yaml, environments/shared-nonprod/README.md, environments/shared-nonprod/kustomization.yaml, environments/shared-preprod/README.md, environments/shared-preprod/kustomization.yaml
Kustomization files taken from here, as per docs: https://github.com/CrunchyData/postgres-operator-examples/
=> Add Crunchy PostgreSQL Operator to staging

environments/staging/kustomization.yaml, environments/test/kustomization.yaml
Bumping test and staging to latest build.
=> Bump frontend to v20230511-27-1f466a27

base/passport-status-db/configmaps.yaml, base/passport-status-db/kustomization.yaml, base/passport-status-db/postgres-clusters.yaml, environments/test/kustomization.yaml
Add a simple PostgresCluster to the test environment to test Crunchy PGO.
=> Add PostgresCluster to test environment

environments/staging/kustomization.yaml
=> Add crunchy database to staging

environments/test/kustomization.yaml
=> Fix error in test environment patches

environments/staging/kustomization.yaml
=> Bring staging in line with test

environments/staging/kustomization.yaml
=> Bump staging API to 20230608-00358-440268d4

environments/test/kustomization.yaml
=> Bump test versions of API and frontend

environments/prod/bitnami-to-crunchy-backup-cronjob.yaml, environments/prod/kustomization.yaml
=> Add bitnami-to-crunchy-backup cronjob

base/passport-status-db/README.md, base/passport-status-db/postgres-clusters.yaml, base/postgres-operator/README.md
See <https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/backups-disaster-recovery/backup-management>
=> Set backup retention to 3

base/passport-status-db/postgres-clusters.yaml, environments/prod/kustomization.yaml, environments/staging/kustomization.yaml
Will need downsizing strategy.
=> Reverting db size overrides to what's live

environments/staging/kustomization.yaml
Business DG wants text from headers present in status/response bodies. This is the shortest path there.
=> Pushing text changes to staging for review.

environments/staging/kustomization.yaml
=> Deploy 3.1 to staging

environments/prod/kustomization.yaml
=> Release 3.1.0

environments/prod/passport-status-api-configmaps.yaml
Was requested to disable canada post manifests again.
=> Disabled canada post manifests due to strike
